---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../9

components:
  - ./metadata
  - ../../components/cpu-topology-spread
  - ../../components/interface-multiqueue

nameSuffix: ".dpdk"
