---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
spec:
  # https://en.opensuse.org/Hardware_requirements
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 2Gi
