version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/tests"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 3
    labels:
      - "release-note-none"
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 3
    labels:
      - "release-note-none"
