---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../common-instancetypes/instancetypes

patches:
  - target:
      kind: VirtualMachineClusterInstancetype
    patch: |-
      apiVersion: instancetype.kubevirt.io/v1alpha2
      metadata:
        name: VirtualMachineClusterInstancetype
      kind: VirtualMachineClusterInstancetype
      $patch: delete
