---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../9/amd64

components:
  - ./metadata
  - ./realtime
  - ./requirements
  - ../../components/cpu-topology-spread
  - ../../components/interface-multiqueue

nameSuffix: ".realtime"
