---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
spec:
  # https://documentation.suse.com/sles/15-SP6/html/SLES-all/cha-x86.html#sec-x86-requirements
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 2Gi
