---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ./metadata
  - ../../components/hyperv
  - ../../components/cpu-topology-sockets
  - ../../components/diskbus-sata
  - ../../components/interfacemodel-e1000e
  - ../../components/tablet-usb
  # Setting termination grace period of 1 hour (3600 secs), because Windows
  # can take longer to shut down or reboot when updates or other changes
  # are applied.
  - ../../components/termination-grace-period

patches:
  - target:
      kind: VirtualMachinePreference
    patch: |-
      - op: replace
        path: /metadata/name
        value: windows
  - target:
      kind: VirtualMachineClusterPreference
    patch: |-
      - op: replace
        path: /metadata/name
        value: windows
