---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterInstancetype
metadata:
  name: "m1.2xlarge"
  labels:
    instancetype.kubevirt.io/cpu: "8"
    instancetype.kubevirt.io/memory: "64Gi"
spec:
  cpu:
    guest: 8
  memory:
    guest: "64Gi"
---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterInstancetype
metadata:
  name: "m1.4xlarge"
  labels:
    instancetype.kubevirt.io/cpu: "16"
    instancetype.kubevirt.io/memory: "128Gi"
spec:
  cpu:
    guest: 16
  memory:
    guest: "128Gi"
---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterInstancetype
metadata:
  name: "m1.8xlarge"
  labels:
    instancetype.kubevirt.io/cpu: "32"
    instancetype.kubevirt.io/memory: "256Gi"
spec:
  cpu:
    guest: 32
  memory:
    guest: "256Gi"
---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterInstancetype
metadata:
  name: "m1.large"
  labels:
    instancetype.kubevirt.io/cpu: "2"
    instancetype.kubevirt.io/memory: "16Gi"
spec:
  cpu:
    guest: 2
  memory:
    guest: "16Gi"
---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterInstancetype
metadata:
  name: "m1.xlarge"
  labels:
    instancetype.kubevirt.io/cpu: "4"
    instancetype.kubevirt.io/memory: "32Gi"
spec:
  cpu:
    guest: 4
  memory:
    guest: "32Gi"
