---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../common-instancetypes/preferences

patches:
  - target:
      kind: VirtualMachineClusterPreference
    patch: |-
      apiVersion: instancetype.kubevirt.io/v1alpha1
      metadata:
        name: VirtualMachineClusterPreference
      kind: VirtualMachineClusterPreference
      $patch: delete
