---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./10_stream_desktop
  - ./10_stream
  - ./9_stream_desktop
  - ./9_stream_dpdk
  - ./9_stream
  - ./8_stream_desktop
  - ./8_stream_dpdk
  - ./8_stream
  - ./7_desktop
  - ./7
