---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: "1"

patches:
  - path: o1.yaml
    target:
      kind: VirtualMachineInstancetype
  - path: o1.yaml
    target:
      kind: VirtualMachineClusterInstancetype
